services:
  - type: web
    name: minecraft-server
    runtime: docker
    privileged: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "5000"
      - key: RENDER_DISK_LIMIT_GB
        value: "18.0"
      - key: FORCE_MAIN
        value: "1"
    healthCheckPath: /api/ping
    disk:
      name: minecraft-disk
      mountPath: /minecraft
      sizeGB: 18
    numInstances: 1
